[versions]
agp = "8.13.1"
kotlin = "2.2.21"
mt-plugin = "1.0.0-alpha5"
desugarJdkLibs = "2.1.5"

[libraries]
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
mt-plugin = { id = "bin.mt.plugin", version.ref = "mt-plugin" }
